// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.1
// source: src/game.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 角色状态机形态
type RoleStatus int32

const (
	RoleStatus_idle   RoleStatus = 0
	RoleStatus_walk   RoleStatus = 1
	RoleStatus_run    RoleStatus = 2
	RoleStatus_jump   RoleStatus = 3
	RoleStatus_crouch RoleStatus = 4
	RoleStatus_climb  RoleStatus = 5
	RoleStatus_deathb RoleStatus = 6
	RoleStatus_deathf RoleStatus = 7
)

// Enum value maps for RoleStatus.
var (
	RoleStatus_name = map[int32]string{
		0: "idle",
		1: "walk",
		2: "run",
		3: "jump",
		4: "crouch",
		5: "climb",
		6: "deathb",
		7: "deathf",
	}
	RoleStatus_value = map[string]int32{
		"idle":   0,
		"walk":   1,
		"run":    2,
		"jump":   3,
		"crouch": 4,
		"climb":  5,
		"deathb": 6,
		"deathf": 7,
	}
)

func (x RoleStatus) Enum() *RoleStatus {
	p := new(RoleStatus)
	*p = x
	return p
}

func (x RoleStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoleStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_src_game_proto_enumTypes[0].Descriptor()
}

func (RoleStatus) Type() protoreflect.EnumType {
	return &file_src_game_proto_enumTypes[0]
}

func (x RoleStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoleStatus.Descriptor instead.
func (RoleStatus) EnumDescriptor() ([]byte, []int) {
	return file_src_game_proto_rawDescGZIP(), []int{0}
}

// 角色方向
type RoleDirction int32

const (
	RoleDirction_up    RoleDirction = 0
	RoleDirction_down  RoleDirction = 1
	RoleDirction_left  RoleDirction = 2
	RoleDirction_right RoleDirction = 4
)

// Enum value maps for RoleDirction.
var (
	RoleDirction_name = map[int32]string{
		0: "up",
		1: "down",
		2: "left",
		4: "right",
	}
	RoleDirction_value = map[string]int32{
		"up":    0,
		"down":  1,
		"left":  2,
		"right": 4,
	}
)

func (x RoleDirction) Enum() *RoleDirction {
	p := new(RoleDirction)
	*p = x
	return p
}

func (x RoleDirction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoleDirction) Descriptor() protoreflect.EnumDescriptor {
	return file_src_game_proto_enumTypes[1].Descriptor()
}

func (RoleDirction) Type() protoreflect.EnumType {
	return &file_src_game_proto_enumTypes[1]
}

func (x RoleDirction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoleDirction.Descriptor instead.
func (RoleDirction) EnumDescriptor() ([]byte, []int) {
	return file_src_game_proto_rawDescGZIP(), []int{1}
}

// buff类型
type BuffType int32

const (
	BuffType_harm   BuffType = 0 // 持续伤害，
	BuffType_repair BuffType = 1 // 持续恢复
	BuffType_speed  BuffType = 2 // 改变角色速度
	BuffType_cool   BuffType = 3 // 改变技能冷却
)

// Enum value maps for BuffType.
var (
	BuffType_name = map[int32]string{
		0: "harm",
		1: "repair",
		2: "speed",
		3: "cool",
	}
	BuffType_value = map[string]int32{
		"harm":   0,
		"repair": 1,
		"speed":  2,
		"cool":   3,
	}
)

func (x BuffType) Enum() *BuffType {
	p := new(BuffType)
	*p = x
	return p
}

func (x BuffType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuffType) Descriptor() protoreflect.EnumDescriptor {
	return file_src_game_proto_enumTypes[2].Descriptor()
}

func (BuffType) Type() protoreflect.EnumType {
	return &file_src_game_proto_enumTypes[2]
}

func (x BuffType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuffType.Descriptor instead.
func (BuffType) EnumDescriptor() ([]byte, []int) {
	return file_src_game_proto_rawDescGZIP(), []int{2}
}

// 玩家属性
type RoleInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lv  int32 `protobuf:"varint,1,opt,name=lv,proto3" json:"lv,omitempty"`
	Exp int32 `protobuf:"varint,2,opt,name=exp,proto3" json:"exp,omitempty"`
	Hp  int32 `protobuf:"varint,3,opt,name=hp,proto3" json:"hp,omitempty"`
	Mp  int32 `protobuf:"varint,4,opt,name=mp,proto3" json:"mp,omitempty"`
	Atk int32 `protobuf:"varint,5,opt,name=atk,proto3" json:"atk,omitempty"`
	Def int32 `protobuf:"varint,6,opt,name=def,proto3" json:"def,omitempty"`
}

func (x *RoleInfo) Reset() {
	*x = RoleInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfo) ProtoMessage() {}

func (x *RoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_src_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfo.ProtoReflect.Descriptor instead.
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return file_src_game_proto_rawDescGZIP(), []int{0}
}

func (x *RoleInfo) GetLv() int32 {
	if x != nil {
		return x.Lv
	}
	return 0
}

func (x *RoleInfo) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *RoleInfo) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *RoleInfo) GetMp() int32 {
	if x != nil {
		return x.Mp
	}
	return 0
}

func (x *RoleInfo) GetAtk() int32 {
	if x != nil {
		return x.Atk
	}
	return 0
}

func (x *RoleInfo) GetDef() int32 {
	if x != nil {
		return x.Def
	}
	return 0
}

type RoleData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X      float32      `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y      float32      `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Status RoleStatus   `protobuf:"varint,4,opt,name=status,proto3,enum=myworld.RoleStatus" json:"status,omitempty"`
	Dirct  RoleDirction `protobuf:"varint,5,opt,name=dirct,proto3,enum=myworld.RoleDirction" json:"dirct,omitempty"`
	Info   *RoleInfo    `protobuf:"bytes,6,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *RoleData) Reset() {
	*x = RoleData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleData) ProtoMessage() {}

func (x *RoleData) ProtoReflect() protoreflect.Message {
	mi := &file_src_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleData.ProtoReflect.Descriptor instead.
func (*RoleData) Descriptor() ([]byte, []int) {
	return file_src_game_proto_rawDescGZIP(), []int{1}
}

func (x *RoleData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleData) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *RoleData) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *RoleData) GetStatus() RoleStatus {
	if x != nil {
		return x.Status
	}
	return RoleStatus_idle
}

func (x *RoleData) GetDirct() RoleDirction {
	if x != nil {
		return x.Dirct
	}
	return RoleDirction_up
}

func (x *RoleData) GetInfo() *RoleInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type BuffData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BuffData) Reset() {
	*x = BuffData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_game_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuffData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuffData) ProtoMessage() {}

func (x *BuffData) ProtoReflect() protoreflect.Message {
	mi := &file_src_game_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuffData.ProtoReflect.Descriptor instead.
func (*BuffData) Descriptor() ([]byte, []int) {
	return file_src_game_proto_rawDescGZIP(), []int{2}
}

func (x *BuffData) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GameFrameData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roles []*RoleData `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	Npcs  []*RoleData `protobuf:"bytes,2,rep,name=npcs,proto3" json:"npcs,omitempty"`
}

func (x *GameFrameData) Reset() {
	*x = GameFrameData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_game_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameFrameData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameFrameData) ProtoMessage() {}

func (x *GameFrameData) ProtoReflect() protoreflect.Message {
	mi := &file_src_game_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameFrameData.ProtoReflect.Descriptor instead.
func (*GameFrameData) Descriptor() ([]byte, []int) {
	return file_src_game_proto_rawDescGZIP(), []int{3}
}

func (x *GameFrameData) GetRoles() []*RoleData {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *GameFrameData) GetNpcs() []*RoleData {
	if x != nil {
		return x.Npcs
	}
	return nil
}

// 释放技能
type UserSkillRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Skillid int32 `protobuf:"varint,1,opt,name=skillid,proto3" json:"skillid,omitempty"`
}

func (x *UserSkillRequest) Reset() {
	*x = UserSkillRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_game_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSkillRequest) ProtoMessage() {}

func (x *UserSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_game_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSkillRequest.ProtoReflect.Descriptor instead.
func (*UserSkillRequest) Descriptor() ([]byte, []int) {
	return file_src_game_proto_rawDescGZIP(), []int{4}
}

func (x *UserSkillRequest) GetSkillid() int32 {
	if x != nil {
		return x.Skillid
	}
	return 0
}

type UserSkillResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Issuccess bool   `protobuf:"varint,1,opt,name=issuccess,proto3" json:"issuccess,omitempty"`
	Tips      string `protobuf:"bytes,2,opt,name=tips,proto3" json:"tips,omitempty"`
}

func (x *UserSkillResponse) Reset() {
	*x = UserSkillResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_game_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSkillResponse) ProtoMessage() {}

func (x *UserSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_game_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSkillResponse.ProtoReflect.Descriptor instead.
func (*UserSkillResponse) Descriptor() ([]byte, []int) {
	return file_src_game_proto_rawDescGZIP(), []int{5}
}

func (x *UserSkillResponse) GetIssuccess() bool {
	if x != nil {
		return x.Issuccess
	}
	return false
}

func (x *UserSkillResponse) GetTips() string {
	if x != nil {
		return x.Tips
	}
	return ""
}

// 释放的技能如果挂buff，或者buff失效
type UserBuffBoard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserBuffBoard) Reset() {
	*x = UserBuffBoard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_game_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserBuffBoard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBuffBoard) ProtoMessage() {}

func (x *UserBuffBoard) ProtoReflect() protoreflect.Message {
	mi := &file_src_game_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBuffBoard.ProtoReflect.Descriptor instead.
func (*UserBuffBoard) Descriptor() ([]byte, []int) {
	return file_src_game_proto_rawDescGZIP(), []int{6}
}

var File_src_game_proto protoreflect.FileDescriptor

var file_src_game_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x72, 0x63, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x6d, 0x79, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x22, 0x70, 0x0a, 0x08, 0x52, 0x6f, 0x6c,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x6c, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x6c, 0x76, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x65, 0x78, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x68, 0x70, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x68, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6d, 0x70, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x6d, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x74, 0x6b, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x74, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x65, 0x66,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x64, 0x65, 0x66, 0x22, 0xb7, 0x01, 0x0a, 0x08,
	0x52, 0x6f, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x01, 0x79, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6d, 0x79, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x52,
	0x6f, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x2b, 0x0a, 0x05, 0x64, 0x69, 0x72, 0x63, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x15, 0x2e, 0x6d, 0x79, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x44,
	0x69, 0x72, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x64, 0x69, 0x72, 0x63, 0x74, 0x12, 0x25,
	0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d,
	0x79, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x1a, 0x0a, 0x08, 0x42, 0x75, 0x66, 0x66, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x5f, 0x0a, 0x0d, 0x47, 0x61, 0x6d, 0x65, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x27, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x79, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x52, 0x6f, 0x6c, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x04, 0x6e,
	0x70, 0x63, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x79, 0x77, 0x6f,
	0x72, 0x6c, 0x64, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x6e, 0x70,
	0x63, 0x73, 0x22, 0x2c, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x69, 0x64,
	0x22, 0x45, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x73, 0x22, 0x0f, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x42,
	0x75, 0x66, 0x66, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x2a, 0x62, 0x0a, 0x0a, 0x52, 0x6f, 0x6c, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x08, 0x0a, 0x04, 0x69, 0x64, 0x6c, 0x65, 0x10, 0x00,
	0x12, 0x08, 0x0a, 0x04, 0x77, 0x61, 0x6c, 0x6b, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x72, 0x75,
	0x6e, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x6a, 0x75, 0x6d, 0x70, 0x10, 0x03, 0x12, 0x0a, 0x0a,
	0x06, 0x63, 0x72, 0x6f, 0x75, 0x63, 0x68, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x63, 0x6c, 0x69,
	0x6d, 0x62, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06, 0x64, 0x65, 0x61, 0x74, 0x68, 0x62, 0x10, 0x06,
	0x12, 0x0a, 0x0a, 0x06, 0x64, 0x65, 0x61, 0x74, 0x68, 0x66, 0x10, 0x07, 0x2a, 0x35, 0x0a, 0x0c,
	0x52, 0x6f, 0x6c, 0x65, 0x44, 0x69, 0x72, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x06, 0x0a, 0x02,
	0x75, 0x70, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x64, 0x6f, 0x77, 0x6e, 0x10, 0x01, 0x12, 0x08,
	0x0a, 0x04, 0x6c, 0x65, 0x66, 0x74, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x72, 0x69, 0x67, 0x68,
	0x74, 0x10, 0x04, 0x2a, 0x35, 0x0a, 0x08, 0x42, 0x75, 0x66, 0x66, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x08, 0x0a, 0x04, 0x68, 0x61, 0x72, 0x6d, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x72, 0x65, 0x70,
	0x61, 0x69, 0x72, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x10, 0x02,
	0x12, 0x08, 0x0a, 0x04, 0x63, 0x6f, 0x6f, 0x6c, 0x10, 0x03, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_game_proto_rawDescOnce sync.Once
	file_src_game_proto_rawDescData = file_src_game_proto_rawDesc
)

func file_src_game_proto_rawDescGZIP() []byte {
	file_src_game_proto_rawDescOnce.Do(func() {
		file_src_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_game_proto_rawDescData)
	})
	return file_src_game_proto_rawDescData
}

var file_src_game_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_src_game_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_src_game_proto_goTypes = []interface{}{
	(RoleStatus)(0),           // 0: myworld.RoleStatus
	(RoleDirction)(0),         // 1: myworld.RoleDirction
	(BuffType)(0),             // 2: myworld.BuffType
	(*RoleInfo)(nil),          // 3: myworld.RoleInfo
	(*RoleData)(nil),          // 4: myworld.RoleData
	(*BuffData)(nil),          // 5: myworld.BuffData
	(*GameFrameData)(nil),     // 6: myworld.GameFrameData
	(*UserSkillRequest)(nil),  // 7: myworld.UserSkillRequest
	(*UserSkillResponse)(nil), // 8: myworld.UserSkillResponse
	(*UserBuffBoard)(nil),     // 9: myworld.UserBuffBoard
}
var file_src_game_proto_depIdxs = []int32{
	0, // 0: myworld.RoleData.status:type_name -> myworld.RoleStatus
	1, // 1: myworld.RoleData.dirct:type_name -> myworld.RoleDirction
	3, // 2: myworld.RoleData.info:type_name -> myworld.RoleInfo
	4, // 3: myworld.GameFrameData.roles:type_name -> myworld.RoleData
	4, // 4: myworld.GameFrameData.npcs:type_name -> myworld.RoleData
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_src_game_proto_init() }
func file_src_game_proto_init() {
	if File_src_game_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_game_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_game_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_game_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuffData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_game_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameFrameData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_game_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSkillRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_game_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSkillResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_game_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserBuffBoard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_game_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_game_proto_goTypes,
		DependencyIndexes: file_src_game_proto_depIdxs,
		EnumInfos:         file_src_game_proto_enumTypes,
		MessageInfos:      file_src_game_proto_msgTypes,
	}.Build()
	File_src_game_proto = out.File
	file_src_game_proto_rawDesc = nil
	file_src_game_proto_goTypes = nil
	file_src_game_proto_depIdxs = nil
}
