// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.1
// source: src/gate.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserStatus int32

const (
	// 离线
	UserStatus_offline UserStatus = 0
	// 在线
	UserStatus_online UserStatus = 1
	// 副本中
	UserStatus_ingame UserStatus = 2
	// 聊天中
	UserStatus_inchat UserStatus = 3
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "offline",
		1: "online",
		2: "ingame",
		3: "inchat",
	}
	UserStatus_value = map[string]int32{
		"offline": 0,
		"online":  1,
		"ingame":  2,
		"inchat":  3,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_src_gate_proto_enumTypes[0].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_src_gate_proto_enumTypes[0]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_src_gate_proto_rawDescGZIP(), []int{0}
}

// 心跳包
type HeartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HeartRequest) Reset() {
	*x = HeartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_gate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartRequest) ProtoMessage() {}

func (x *HeartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_gate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartRequest.ProtoReflect.Descriptor instead.
func (*HeartRequest) Descriptor() ([]byte, []int) {
	return file_src_gate_proto_rawDescGZIP(), []int{0}
}

type HeartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HeartResponse) Reset() {
	*x = HeartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_gate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartResponse) ProtoMessage() {}

func (x *HeartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_gate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartResponse.ProtoReflect.Descriptor instead.
func (*HeartResponse) Descriptor() ([]byte, []int) {
	return file_src_gate_proto_rawDescGZIP(), []int{1}
}

// 重连，除副本外，直接拉回游戏服，
type ReconnextRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReconnextRequest) Reset() {
	*x = ReconnextRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_gate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReconnextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnextRequest) ProtoMessage() {}

func (x *ReconnextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_gate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnextRequest.ProtoReflect.Descriptor instead.
func (*ReconnextRequest) Descriptor() ([]byte, []int) {
	return file_src_gate_proto_rawDescGZIP(), []int{2}
}

type ReconnectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status UserStatus `protobuf:"varint,1,opt,name=status,proto3,enum=myworld.UserStatus" json:"status,omitempty"`
	Gameid int64      `protobuf:"varint,2,opt,name=gameid,proto3" json:"gameid,omitempty"`
}

func (x *ReconnectResponse) Reset() {
	*x = ReconnectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_gate_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnectResponse) ProtoMessage() {}

func (x *ReconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_gate_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnectResponse.ProtoReflect.Descriptor instead.
func (*ReconnectResponse) Descriptor() ([]byte, []int) {
	return file_src_gate_proto_rawDescGZIP(), []int{3}
}

func (x *ReconnectResponse) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_offline
}

func (x *ReconnectResponse) GetGameid() int64 {
	if x != nil {
		return x.Gameid
	}
	return 0
}

// 强制修改玩家状态，强踢/强拉等
type ChangeUserStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status UserStatus `protobuf:"varint,1,opt,name=status,proto3,enum=myworld.UserStatus" json:"status,omitempty"`
	Gameid int64      `protobuf:"varint,2,opt,name=gameid,proto3" json:"gameid,omitempty"`
}

func (x *ChangeUserStatus) Reset() {
	*x = ChangeUserStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_gate_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeUserStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserStatus) ProtoMessage() {}

func (x *ChangeUserStatus) ProtoReflect() protoreflect.Message {
	mi := &file_src_gate_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserStatus.ProtoReflect.Descriptor instead.
func (*ChangeUserStatus) Descriptor() ([]byte, []int) {
	return file_src_gate_proto_rawDescGZIP(), []int{4}
}

func (x *ChangeUserStatus) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_offline
}

func (x *ChangeUserStatus) GetGameid() int64 {
	if x != nil {
		return x.Gameid
	}
	return 0
}

var File_src_gate_proto protoreflect.FileDescriptor

var file_src_gate_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x72, 0x63, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x6d, 0x79, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x22, 0x0e, 0x0a, 0x0c, 0x48, 0x65, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x48, 0x65, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x52, 0x65,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x58,
	0x0a, 0x11, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6d, 0x79, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x69, 0x64, 0x22, 0x57, 0x0a, 0x10, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2b, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6d,
	0x79, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d,
	0x65, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x69,
	0x64, 0x2a, 0x3d, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x0b, 0x0a, 0x07, 0x6f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x69, 0x6e, 0x67, 0x61,
	0x6d, 0x65, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x69, 0x6e, 0x63, 0x68, 0x61, 0x74, 0x10, 0x03,
	0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_gate_proto_rawDescOnce sync.Once
	file_src_gate_proto_rawDescData = file_src_gate_proto_rawDesc
)

func file_src_gate_proto_rawDescGZIP() []byte {
	file_src_gate_proto_rawDescOnce.Do(func() {
		file_src_gate_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_gate_proto_rawDescData)
	})
	return file_src_gate_proto_rawDescData
}

var file_src_gate_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_src_gate_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_src_gate_proto_goTypes = []interface{}{
	(UserStatus)(0),           // 0: myworld.UserStatus
	(*HeartRequest)(nil),      // 1: myworld.HeartRequest
	(*HeartResponse)(nil),     // 2: myworld.HeartResponse
	(*ReconnextRequest)(nil),  // 3: myworld.ReconnextRequest
	(*ReconnectResponse)(nil), // 4: myworld.ReconnectResponse
	(*ChangeUserStatus)(nil),  // 5: myworld.ChangeUserStatus
}
var file_src_gate_proto_depIdxs = []int32{
	0, // 0: myworld.ReconnectResponse.status:type_name -> myworld.UserStatus
	0, // 1: myworld.ChangeUserStatus.status:type_name -> myworld.UserStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_src_gate_proto_init() }
func file_src_gate_proto_init() {
	if File_src_gate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_gate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_gate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_gate_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReconnextRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_gate_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReconnectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_gate_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeUserStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_gate_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_gate_proto_goTypes,
		DependencyIndexes: file_src_gate_proto_depIdxs,
		EnumInfos:         file_src_gate_proto_enumTypes,
		MessageInfos:      file_src_gate_proto_msgTypes,
	}.Build()
	File_src_gate_proto = out.File
	file_src_gate_proto_rawDesc = nil
	file_src_gate_proto_goTypes = nil
	file_src_gate_proto_depIdxs = nil
}
