// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.1
// source: src/chat.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatType int32

const (
	// 私聊
	ChatType_Single ChatType = 0
	// 群聊
	ChatType_Group ChatType = 1
	// 全服
	ChatType_ALL ChatType = 2
	// 邮件
	ChatType_Email ChatType = 3
)

// Enum value maps for ChatType.
var (
	ChatType_name = map[int32]string{
		0: "Single",
		1: "Group",
		2: "ALL",
		3: "Email",
	}
	ChatType_value = map[string]int32{
		"Single": 0,
		"Group":  1,
		"ALL":    2,
		"Email":  3,
	}
)

func (x ChatType) Enum() *ChatType {
	p := new(ChatType)
	*p = x
	return p
}

func (x ChatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatType) Descriptor() protoreflect.EnumDescriptor {
	return file_src_chat_proto_enumTypes[0].Descriptor()
}

func (ChatType) Type() protoreflect.EnumType {
	return &file_src_chat_proto_enumTypes[0]
}

func (x ChatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatType.Descriptor instead.
func (ChatType) EnumDescriptor() ([]byte, []int) {
	return file_src_chat_proto_rawDescGZIP(), []int{0}
}

// 不存在相同的用户id和群id，系统id为0
type GetMessageBoard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mid     int64    `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	Fromid  int64    `protobuf:"varint,2,opt,name=fromid,proto3" json:"fromid,omitempty"`
	Type    ChatType `protobuf:"varint,3,opt,name=type,proto3,enum=myworld.ChatType" json:"type,omitempty"`
	Content string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Groupid int64    `protobuf:"varint,5,opt,name=groupid,proto3" json:"groupid,omitempty"`
}

func (x *GetMessageBoard) Reset() {
	*x = GetMessageBoard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_chat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMessageBoard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageBoard) ProtoMessage() {}

func (x *GetMessageBoard) ProtoReflect() protoreflect.Message {
	mi := &file_src_chat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageBoard.ProtoReflect.Descriptor instead.
func (*GetMessageBoard) Descriptor() ([]byte, []int) {
	return file_src_chat_proto_rawDescGZIP(), []int{0}
}

func (x *GetMessageBoard) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *GetMessageBoard) GetFromid() int64 {
	if x != nil {
		return x.Fromid
	}
	return 0
}

func (x *GetMessageBoard) GetType() ChatType {
	if x != nil {
		return x.Type
	}
	return ChatType_Single
}

func (x *GetMessageBoard) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetMessageBoard) GetGroupid() int64 {
	if x != nil {
		return x.Groupid
	}
	return 0
}

// 发送消息,mid不为0时，表示引用该消息
type UserChatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Toid    int64  `protobuf:"varint,1,opt,name=toid,proto3" json:"toid,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *UserChatRequest) Reset() {
	*x = UserChatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_chat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserChatRequest) ProtoMessage() {}

func (x *UserChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_chat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserChatRequest.ProtoReflect.Descriptor instead.
func (*UserChatRequest) Descriptor() ([]byte, []int) {
	return file_src_chat_proto_rawDescGZIP(), []int{1}
}

func (x *UserChatRequest) GetToid() int64 {
	if x != nil {
		return x.Toid
	}
	return 0
}

func (x *UserChatRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 只表示是否成功发送消息
type UserChatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Issuccess bool   `protobuf:"varint,1,opt,name=issuccess,proto3" json:"issuccess,omitempty"`
	Tips      string `protobuf:"bytes,2,opt,name=tips,proto3" json:"tips,omitempty"`
}

func (x *UserChatResponse) Reset() {
	*x = UserChatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_chat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserChatResponse) ProtoMessage() {}

func (x *UserChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_chat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserChatResponse.ProtoReflect.Descriptor instead.
func (*UserChatResponse) Descriptor() ([]byte, []int) {
	return file_src_chat_proto_rawDescGZIP(), []int{2}
}

func (x *UserChatResponse) GetIssuccess() bool {
	if x != nil {
		return x.Issuccess
	}
	return false
}

func (x *UserChatResponse) GetTips() string {
	if x != nil {
		return x.Tips
	}
	return ""
}

// 屏蔽用户
type ShieldChatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShieldID int64 `protobuf:"varint,1,opt,name=shieldID,proto3" json:"shieldID,omitempty"`
}

func (x *ShieldChatRequest) Reset() {
	*x = ShieldChatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_chat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShieldChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShieldChatRequest) ProtoMessage() {}

func (x *ShieldChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_chat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShieldChatRequest.ProtoReflect.Descriptor instead.
func (*ShieldChatRequest) Descriptor() ([]byte, []int) {
	return file_src_chat_proto_rawDescGZIP(), []int{3}
}

func (x *ShieldChatRequest) GetShieldID() int64 {
	if x != nil {
		return x.ShieldID
	}
	return 0
}

type ShieldChatResponese struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Issuccess bool   `protobuf:"varint,1,opt,name=issuccess,proto3" json:"issuccess,omitempty"`
	Tips      string `protobuf:"bytes,2,opt,name=tips,proto3" json:"tips,omitempty"`
}

func (x *ShieldChatResponese) Reset() {
	*x = ShieldChatResponese{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_chat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShieldChatResponese) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShieldChatResponese) ProtoMessage() {}

func (x *ShieldChatResponese) ProtoReflect() protoreflect.Message {
	mi := &file_src_chat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShieldChatResponese.ProtoReflect.Descriptor instead.
func (*ShieldChatResponese) Descriptor() ([]byte, []int) {
	return file_src_chat_proto_rawDescGZIP(), []int{4}
}

func (x *ShieldChatResponese) GetIssuccess() bool {
	if x != nil {
		return x.Issuccess
	}
	return false
}

func (x *ShieldChatResponese) GetTips() string {
	if x != nil {
		return x.Tips
	}
	return ""
}

var File_src_chat_proto protoreflect.FileDescriptor

var file_src_chat_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x72, 0x63, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x6d, 0x79, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x22, 0x96, 0x01, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6d, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x66, 0x72, 0x6f, 0x6d, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x6d, 0x79, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e,
	0x43, 0x68, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x69, 0x64, 0x22, 0x3f, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x6f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x6f, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x22, 0x44, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x43, 0x68, 0x61, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x73, 0x22, 0x2f, 0x0a, 0x11, 0x53, 0x68, 0x69,
	0x65, 0x6c, 0x64, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x73, 0x68, 0x69, 0x65, 0x6c, 0x64, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x73, 0x68, 0x69, 0x65, 0x6c, 0x64, 0x49, 0x44, 0x22, 0x47, 0x0a, 0x13, 0x53, 0x68,
	0x69, 0x65, 0x6c, 0x64, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x73,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x69, 0x70, 0x73, 0x2a, 0x35, 0x0a, 0x08, 0x43, 0x68, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0a, 0x0a, 0x06, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x4c, 0x4c, 0x10, 0x02, 0x12,
	0x09, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x10, 0x03, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_chat_proto_rawDescOnce sync.Once
	file_src_chat_proto_rawDescData = file_src_chat_proto_rawDesc
)

func file_src_chat_proto_rawDescGZIP() []byte {
	file_src_chat_proto_rawDescOnce.Do(func() {
		file_src_chat_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_chat_proto_rawDescData)
	})
	return file_src_chat_proto_rawDescData
}

var file_src_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_src_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_src_chat_proto_goTypes = []interface{}{
	(ChatType)(0),               // 0: myworld.ChatType
	(*GetMessageBoard)(nil),     // 1: myworld.GetMessageBoard
	(*UserChatRequest)(nil),     // 2: myworld.UserChatRequest
	(*UserChatResponse)(nil),    // 3: myworld.UserChatResponse
	(*ShieldChatRequest)(nil),   // 4: myworld.ShieldChatRequest
	(*ShieldChatResponese)(nil), // 5: myworld.ShieldChatResponese
}
var file_src_chat_proto_depIdxs = []int32{
	0, // 0: myworld.GetMessageBoard.type:type_name -> myworld.ChatType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_chat_proto_init() }
func file_src_chat_proto_init() {
	if File_src_chat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_chat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMessageBoard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_chat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserChatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_chat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserChatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_chat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShieldChatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_chat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShieldChatResponese); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_chat_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_chat_proto_goTypes,
		DependencyIndexes: file_src_chat_proto_depIdxs,
		EnumInfos:         file_src_chat_proto_enumTypes,
		MessageInfos:      file_src_chat_proto_msgTypes,
	}.Build()
	File_src_chat_proto = out.File
	file_src_chat_proto_rawDesc = nil
	file_src_chat_proto_goTypes = nil
	file_src_chat_proto_depIdxs = nil
}
