// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.1
// source: src/hall.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Map string  `protobuf:"bytes,1,opt,name=map,proto3" json:"map,omitempty"`
	X   float32 `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y   float32 `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *UserPosition) Reset() {
	*x = UserPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_hall_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPosition) ProtoMessage() {}

func (x *UserPosition) ProtoReflect() protoreflect.Message {
	mi := &file_src_hall_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPosition.ProtoReflect.Descriptor instead.
func (*UserPosition) Descriptor() ([]byte, []int) {
	return file_src_hall_proto_rawDescGZIP(), []int{0}
}

func (x *UserPosition) GetMap() string {
	if x != nil {
		return x.Map
	}
	return ""
}

func (x *UserPosition) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *UserPosition) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nick    string `protobuf:"bytes,1,opt,name=nick,proto3" json:"nick,omitempty"`       // 昵称
	Head    string `protobuf:"bytes,2,opt,name=head,proto3" json:"head,omitempty"`       // 头像
	Birth   int64  `protobuf:"varint,3,opt,name=birth,proto3" json:"birth,omitempty"`    // 生日
	Phone   int64  `protobuf:"varint,4,opt,name=phone,proto3" json:"phone,omitempty"`    // 手机
	Address string `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"` // 住址
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_hall_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_src_hall_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_src_hall_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfo) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *UserInfo) GetHead() string {
	if x != nil {
		return x.Head
	}
	return ""
}

func (x *UserInfo) GetBirth() int64 {
	if x != nil {
		return x.Birth
	}
	return 0
}

func (x *UserInfo) GetPhone() int64 {
	if x != nil {
		return x.Phone
	}
	return 0
}

func (x *UserInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type UserAvatar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Avatar string `protobuf:"bytes,1,opt,name=avatar,proto3" json:"avatar,omitempty"` // 装扮，后面要拆分
}

func (x *UserAvatar) Reset() {
	*x = UserAvatar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_hall_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAvatar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAvatar) ProtoMessage() {}

func (x *UserAvatar) ProtoReflect() protoreflect.Message {
	mi := &file_src_hall_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAvatar.ProtoReflect.Descriptor instead.
func (*UserAvatar) Descriptor() ([]byte, []int) {
	return file_src_hall_proto_rawDescGZIP(), []int{2}
}

func (x *UserAvatar) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

// 用户数据
type UserData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Info   *UserInfo     `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Avatar *UserAvatar   `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Pos    *UserPosition `protobuf:"bytes,4,opt,name=pos,proto3" json:"pos,omitempty"`
}

func (x *UserData) Reset() {
	*x = UserData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_hall_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserData) ProtoMessage() {}

func (x *UserData) ProtoReflect() protoreflect.Message {
	mi := &file_src_hall_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserData.ProtoReflect.Descriptor instead.
func (*UserData) Descriptor() ([]byte, []int) {
	return file_src_hall_proto_rawDescGZIP(), []int{3}
}

func (x *UserData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserData) GetInfo() *UserInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *UserData) GetAvatar() *UserAvatar {
	if x != nil {
		return x.Avatar
	}
	return nil
}

func (x *UserData) GetPos() *UserPosition {
	if x != nil {
		return x.Pos
	}
	return nil
}

// 每0.1s合并一次数据，通过frameData发给客户端
type HallFrameData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Self   *UserData   `protobuf:"bytes,1,opt,name=self,proto3" json:"self,omitempty"`
	Others []*UserData `protobuf:"bytes,2,rep,name=others,proto3" json:"others,omitempty"`
}

func (x *HallFrameData) Reset() {
	*x = HallFrameData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_hall_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HallFrameData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HallFrameData) ProtoMessage() {}

func (x *HallFrameData) ProtoReflect() protoreflect.Message {
	mi := &file_src_hall_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HallFrameData.ProtoReflect.Descriptor instead.
func (*HallFrameData) Descriptor() ([]byte, []int) {
	return file_src_hall_proto_rawDescGZIP(), []int{4}
}

func (x *HallFrameData) GetSelf() *UserData {
	if x != nil {
		return x.Self
	}
	return nil
}

func (x *HallFrameData) GetOthers() []*UserData {
	if x != nil {
		return x.Others
	}
	return nil
}

// 用户进入游戏
type UserEnterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserEnterRequest) Reset() {
	*x = UserEnterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_hall_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserEnterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEnterRequest) ProtoMessage() {}

func (x *UserEnterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_hall_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEnterRequest.ProtoReflect.Descriptor instead.
func (*UserEnterRequest) Descriptor() ([]byte, []int) {
	return file_src_hall_proto_rawDescGZIP(), []int{5}
}

type UserEnterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Self   *UserData   `protobuf:"bytes,1,opt,name=self,proto3" json:"self,omitempty"`
	Others []*UserData `protobuf:"bytes,2,rep,name=others,proto3" json:"others,omitempty"`
}

func (x *UserEnterResponse) Reset() {
	*x = UserEnterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_hall_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserEnterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEnterResponse) ProtoMessage() {}

func (x *UserEnterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_hall_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEnterResponse.ProtoReflect.Descriptor instead.
func (*UserEnterResponse) Descriptor() ([]byte, []int) {
	return file_src_hall_proto_rawDescGZIP(), []int{6}
}

func (x *UserEnterResponse) GetSelf() *UserData {
	if x != nil {
		return x.Self
	}
	return nil
}

func (x *UserEnterResponse) GetOthers() []*UserData {
	if x != nil {
		return x.Others
	}
	return nil
}

// 用户移动
type UserMoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserMoveRequest) Reset() {
	*x = UserMoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_hall_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMoveRequest) ProtoMessage() {}

func (x *UserMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_hall_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMoveRequest.ProtoReflect.Descriptor instead.
func (*UserMoveRequest) Descriptor() ([]byte, []int) {
	return file_src_hall_proto_rawDescGZIP(), []int{7}
}

type UserMoveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Issuccess bool   `protobuf:"varint,1,opt,name=issuccess,proto3" json:"issuccess,omitempty"`
	Tips      string `protobuf:"bytes,2,opt,name=tips,proto3" json:"tips,omitempty"`
}

func (x *UserMoveResponse) Reset() {
	*x = UserMoveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_hall_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserMoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMoveResponse) ProtoMessage() {}

func (x *UserMoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_hall_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMoveResponse.ProtoReflect.Descriptor instead.
func (*UserMoveResponse) Descriptor() ([]byte, []int) {
	return file_src_hall_proto_rawDescGZIP(), []int{8}
}

func (x *UserMoveResponse) GetIssuccess() bool {
	if x != nil {
		return x.Issuccess
	}
	return false
}

func (x *UserMoveResponse) GetTips() string {
	if x != nil {
		return x.Tips
	}
	return ""
}

// 修改用户基础信息
type ChangeUserInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *UserInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *ChangeUserInfoRequest) Reset() {
	*x = ChangeUserInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_hall_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserInfoRequest) ProtoMessage() {}

func (x *ChangeUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_hall_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserInfoRequest.ProtoReflect.Descriptor instead.
func (*ChangeUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_src_hall_proto_rawDescGZIP(), []int{9}
}

func (x *ChangeUserInfoRequest) GetInfo() *UserInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type ChangeUserInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Issuccess bool   `protobuf:"varint,1,opt,name=issuccess,proto3" json:"issuccess,omitempty"`
	Tips      string `protobuf:"bytes,2,opt,name=tips,proto3" json:"tips,omitempty"`
}

func (x *ChangeUserInfoResponse) Reset() {
	*x = ChangeUserInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_hall_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserInfoResponse) ProtoMessage() {}

func (x *ChangeUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_hall_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserInfoResponse.ProtoReflect.Descriptor instead.
func (*ChangeUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_src_hall_proto_rawDescGZIP(), []int{10}
}

func (x *ChangeUserInfoResponse) GetIssuccess() bool {
	if x != nil {
		return x.Issuccess
	}
	return false
}

func (x *ChangeUserInfoResponse) GetTips() string {
	if x != nil {
		return x.Tips
	}
	return ""
}

// 修改用户装扮
type ChangeUserAvatarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Avatar string `protobuf:"bytes,1,opt,name=avatar,proto3" json:"avatar,omitempty"`
}

func (x *ChangeUserAvatarRequest) Reset() {
	*x = ChangeUserAvatarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_hall_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeUserAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserAvatarRequest) ProtoMessage() {}

func (x *ChangeUserAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_hall_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserAvatarRequest.ProtoReflect.Descriptor instead.
func (*ChangeUserAvatarRequest) Descriptor() ([]byte, []int) {
	return file_src_hall_proto_rawDescGZIP(), []int{11}
}

func (x *ChangeUserAvatarRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type ChangeUserAvatarResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Issuccess bool   `protobuf:"varint,1,opt,name=issuccess,proto3" json:"issuccess,omitempty"`
	Tips      string `protobuf:"bytes,2,opt,name=tips,proto3" json:"tips,omitempty"`
	Avatar    string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
}

func (x *ChangeUserAvatarResponse) Reset() {
	*x = ChangeUserAvatarResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_hall_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeUserAvatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeUserAvatarResponse) ProtoMessage() {}

func (x *ChangeUserAvatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_hall_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeUserAvatarResponse.ProtoReflect.Descriptor instead.
func (*ChangeUserAvatarResponse) Descriptor() ([]byte, []int) {
	return file_src_hall_proto_rawDescGZIP(), []int{12}
}

func (x *ChangeUserAvatarResponse) GetIssuccess() bool {
	if x != nil {
		return x.Issuccess
	}
	return false
}

func (x *ChangeUserAvatarResponse) GetTips() string {
	if x != nil {
		return x.Tips
	}
	return ""
}

func (x *ChangeUserAvatarResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

var File_src_hall_proto protoreflect.FileDescriptor

var file_src_hall_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x72, 0x63, 0x2f, 0x68, 0x61, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x6d, 0x79, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x22, 0x3c, 0x0a, 0x0c, 0x55, 0x73, 0x65,
	0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x61, 0x70, 0x12, 0x0c, 0x0a, 0x01, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x22, 0x78, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x62,
	0x69, 0x72, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x62, 0x69, 0x72, 0x74,
	0x68, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x22, 0x24, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x22, 0x97, 0x01, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x79, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x2b, 0x0a, 0x06, 0x61,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x79,
	0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x27, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x79, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x70, 0x6f,
	0x73, 0x22, 0x61, 0x0a, 0x0d, 0x48, 0x61, 0x6c, 0x6c, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x25, 0x0a, 0x04, 0x73, 0x65, 0x6c, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x6d, 0x79, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x04, 0x73, 0x65, 0x6c, 0x66, 0x12, 0x29, 0x0a, 0x06, 0x6f, 0x74, 0x68,
	0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x79, 0x77, 0x6f,
	0x72, 0x6c, 0x64, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x06, 0x6f, 0x74,
	0x68, 0x65, 0x72, 0x73, 0x22, 0x12, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x65, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72,
	0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a,
	0x04, 0x73, 0x65, 0x6c, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x79,
	0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04,
	0x73, 0x65, 0x6c, 0x66, 0x12, 0x29, 0x0a, 0x06, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x79, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x06, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x73, 0x22,
	0x11, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x44, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x70, 0x73, 0x22, 0x3e, 0x0a, 0x15, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x25, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x6d, 0x79, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x4a, 0x0a, 0x16, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x69, 0x70, 0x73, 0x22, 0x31, 0x0a, 0x17, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x22, 0x64, 0x0a, 0x18, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x69, 0x70, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x42, 0x03, 0x5a,
	0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_hall_proto_rawDescOnce sync.Once
	file_src_hall_proto_rawDescData = file_src_hall_proto_rawDesc
)

func file_src_hall_proto_rawDescGZIP() []byte {
	file_src_hall_proto_rawDescOnce.Do(func() {
		file_src_hall_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_hall_proto_rawDescData)
	})
	return file_src_hall_proto_rawDescData
}

var file_src_hall_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_src_hall_proto_goTypes = []interface{}{
	(*UserPosition)(nil),             // 0: myworld.UserPosition
	(*UserInfo)(nil),                 // 1: myworld.UserInfo
	(*UserAvatar)(nil),               // 2: myworld.UserAvatar
	(*UserData)(nil),                 // 3: myworld.UserData
	(*HallFrameData)(nil),            // 4: myworld.HallFrameData
	(*UserEnterRequest)(nil),         // 5: myworld.UserEnterRequest
	(*UserEnterResponse)(nil),        // 6: myworld.UserEnterResponse
	(*UserMoveRequest)(nil),          // 7: myworld.UserMoveRequest
	(*UserMoveResponse)(nil),         // 8: myworld.UserMoveResponse
	(*ChangeUserInfoRequest)(nil),    // 9: myworld.ChangeUserInfoRequest
	(*ChangeUserInfoResponse)(nil),   // 10: myworld.ChangeUserInfoResponse
	(*ChangeUserAvatarRequest)(nil),  // 11: myworld.ChangeUserAvatarRequest
	(*ChangeUserAvatarResponse)(nil), // 12: myworld.ChangeUserAvatarResponse
}
var file_src_hall_proto_depIdxs = []int32{
	1, // 0: myworld.UserData.info:type_name -> myworld.UserInfo
	2, // 1: myworld.UserData.avatar:type_name -> myworld.UserAvatar
	0, // 2: myworld.UserData.pos:type_name -> myworld.UserPosition
	3, // 3: myworld.HallFrameData.self:type_name -> myworld.UserData
	3, // 4: myworld.HallFrameData.others:type_name -> myworld.UserData
	3, // 5: myworld.UserEnterResponse.self:type_name -> myworld.UserData
	3, // 6: myworld.UserEnterResponse.others:type_name -> myworld.UserData
	1, // 7: myworld.ChangeUserInfoRequest.info:type_name -> myworld.UserInfo
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_src_hall_proto_init() }
func file_src_hall_proto_init() {
	if File_src_hall_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_hall_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_hall_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_hall_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAvatar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_hall_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_hall_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HallFrameData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_hall_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserEnterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_hall_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserEnterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_hall_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserMoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_hall_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserMoveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_hall_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeUserInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_hall_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeUserInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_hall_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeUserAvatarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_hall_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeUserAvatarResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_hall_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_hall_proto_goTypes,
		DependencyIndexes: file_src_hall_proto_depIdxs,
		MessageInfos:      file_src_hall_proto_msgTypes,
	}.Build()
	File_src_hall_proto = out.File
	file_src_hall_proto_rawDesc = nil
	file_src_hall_proto_goTypes = nil
	file_src_hall_proto_depIdxs = nil
}
